spring:
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://unit-cookies.cisvczdknmdb.ap-northeast-2.rds.amazonaws.com:3306/unitcookiesdb
    username: unitcookies
    password: unitcookies
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

front-client:
  #  domain: